replicaCount: 1

image:
  repository: bechir19/order-service
  pullPolicy: Never
  tag: "v3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8081
  annotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8081" # Doit correspondre au port de l'application

ingress:
  enabled: false # Désactivé pour simplifier si vous utilisez la Gateway
  className: ""
  annotations: {}
  hosts:
    - host: order-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false

resources:
  # On définit des limites pour éviter que ce service ne mange toute la RAM de la VM
  limits:
    memory: "768Mi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "200m"

# CONFIGURATION DES PROBES CORRIGÉE
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8081          # Utilisation du port direct
  initialDelaySeconds: 120 # 2 minutes pour laisser le temps à Hibernate/Flyway/Kafka
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 10     # Très important sur une VM lente

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 100
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 10

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
