replicaCount: 1

image:
  repository: bechir19/api-gateway
  tag: "v4"
  pullPolicy: Never

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Annotations pour le POD (Aide Prometheus à trouver le container)
podAnnotations: 
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "9000" # Port de la Gateway

podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  # Port exposé par le service K8s
  port: 9000
  # Port réel de l'application défini dans application.properties
  targetPort: 9000
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "9000"

ingress:
  enabled: false # On passe par le port-forward ou un Ingress controller global

# Limites de ressources pour éviter de saturer la RAM VMware
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 200m
    memory: 512Mi

# CONFIGURATION DES PROBES (Vérification de santé)
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 9000          # Utilisation du port 9000 direct
  initialDelaySeconds: 120 # Très important : laisse 2 min à la Gateway pour démarrer
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 9000
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 10

autoscaling:
  enabled: false

httpRoute:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
