apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.59.4  # Cette version installe Grafana 10.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
